; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[admin][version] = "2.0-beta3"

projects[admin_menu][version] = "3.0-rc4"

projects[boxes][version] = "1.1"

projects[browscap][version] = "2.0"

projects[ctools][version] = "1.3"

projects[ckeditor][version] = "1.13"

projects[content_access][version] = "1.2-beta1"

projects[context][version] = "3.0-beta6"

projects[date][version] = "2.6"

projects[devel][version] = "1.3"

projects[ds][version] = "1.7"

projects[email][version] = "1.2"

projects[exclude_node_title][version] = "1.6"

projects[faq][version] = "1.0-rc2"

projects[feeds][version] = "2.0-alpha7"

projects[feeds_sql][version] = "1.0"

projects[field_group][version] = "1.1"

projects[front][version] = "2.3"

projects[google_analytics][version] = "1.3"

projects[imagemagick][version] = "1.0"

projects[imce][version] = "1.7"

projects[imce_filefield][version] = "1.x-dev"

projects[imce_mkdir][version] = "1.0"

projects[jcarousel][version] = "2.6"

projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_plugin][version] = "1.0"

projects[libraries][version] = "2.1"

projects[lightbox2][version] = "1.0-beta1"

projects[link][version] = "1.1"

projects[menu_block][version] = "2.3"

projects[references][version] = "2.1"

projects[page_title][version] = "2.7"

projects[pathauto][version] = "1.2"

projects[plupload][version] = "1.1"

projects[scheduler][version] = "1.0"

projects[site_verify][version] = "1.0"

projects[superfish][version] = "1.8"

projects[tagclouds][version] = "1.9"

projects[textimage][version] = "2.0"

projects[tipsy][version] = "1.0-rc1"

projects[token][version] = "1.5"

projects[views][version] = "3.7"

projects[xmlsitemap][version] = "2.0-rc2"

; Themes
projects[adaptivetheme][version] = "3.1"

projects[analytic][version] = "1.x-dev"

projects[basic][version] = "2.1"

; Modules




; Themes

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[superfish][download][type] = "get"
libraries[superfish][download][url] = "https://github.com/mehrpadin/Superfish-for-Drupal/archive/1571b1d5d3519246fe5b2e40a14579758afac503.zip"
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.4.5/ckeditor_4.4.5_full.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"





